// <auto-generated />
using System;
using IrisManager.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IrisManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260805072056_UpdateServiceDurations")]
    partial class UpdateServiceDurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IrisManager.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StylistId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("IrisManager.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "maria@correo.com",
                            IsActive = true,
                            Name = "María Pérez",
                            Phone = "809-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Email = "juan@correo.com",
                            IsActive = true,
                            Name = "Juan Rodríguez",
                            Phone = "809-555-0202"
                        });
                });

            modelBuilder.Entity("IrisManager.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 45,
                            Name = "Lavado y Secado",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 60,
                            Name = "Corte de Cabello (Dama)",
                            Price = 800m
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 30,
                            Name = "Corte de Cabello (Caballero)",
                            Price = 400m
                        },
                        new
                        {
                            Id = 4,
                            DurationMinutes = 30,
                            Name = "Corte de Puntas",
                            Price = 300m
                        },
                        new
                        {
                            Id = 5,
                            DurationMinutes = 90,
                            Name = "Peinado Elaborado / Eventos",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 6,
                            DurationMinutes = 120,
                            Name = "Tinte Completo",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 7,
                            DurationMinutes = 60,
                            Name = "Retoque de Raíces",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 8,
                            DurationMinutes = 180,
                            Name = "Highlights / Rayitos",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 9,
                            DurationMinutes = 240,
                            Name = "Balayage",
                            Price = 4500m
                        },
                        new
                        {
                            Id = 10,
                            DurationMinutes = 180,
                            Name = "Aplicación de Keratina",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 11,
                            DurationMinutes = 120,
                            Name = "Cirugía Capilar / Botox",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 12,
                            DurationMinutes = 45,
                            Name = "Tratamiento Profundo (Mascarilla)",
                            Price = 600m
                        },
                        new
                        {
                            Id = 13,
                            DurationMinutes = 45,
                            Name = "Manicura Regular",
                            Price = 400m
                        },
                        new
                        {
                            Id = 14,
                            DurationMinutes = 60,
                            Name = "Pedicura Regular",
                            Price = 600m
                        },
                        new
                        {
                            Id = 15,
                            DurationMinutes = 120,
                            Name = "Uñas Acrílicas",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 16,
                            DurationMinutes = 90,
                            Name = "Relleno de Acrílico",
                            Price = 900m
                        },
                        new
                        {
                            Id = 17,
                            DurationMinutes = 60,
                            Name = "Esmaltado en Gel",
                            Price = 700m
                        },
                        new
                        {
                            Id = 18,
                            DurationMinutes = 30,
                            Name = "Retiro de Acrílico / Gel",
                            Price = 300m
                        },
                        new
                        {
                            Id = 19,
                            DurationMinutes = 20,
                            Name = "Diseño y Depilación de Cejas",
                            Price = 300m
                        },
                        new
                        {
                            Id = 20,
                            DurationMinutes = 30,
                            Name = "Tintado de Cejas",
                            Price = 400m
                        },
                        new
                        {
                            Id = 21,
                            DurationMinutes = 30,
                            Name = "Depilación Facial (Cera)",
                            Price = 500m
                        },
                        new
                        {
                            Id = 22,
                            DurationMinutes = 120,
                            Name = "Postura de Pestañas (Pelo a Pelo)",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 23,
                            DurationMinutes = 90,
                            Name = "Maquillaje Profesional",
                            Price = 2500m
                        });
                });

            modelBuilder.Entity("IrisManager.Domain.Entities.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stylists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "",
                            IsActive = true,
                            Name = "Ana (Especialista en Uñas)",
                            Phone = "",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 2,
                            Email = "",
                            IsActive = true,
                            Name = "Carmen (Colorista y Peluquera)",
                            Phone = "",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 3,
                            Email = "",
                            IsActive = true,
                            Name = "Luis (Barbero)",
                            Phone = "",
                            Specialty = ""
                        });
                });

            modelBuilder.Entity("IrisManager.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("IrisManager.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IrisManager.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IrisManager.Domain.Entities.Stylist", "Stylist")
                        .WithMany()
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("Stylist");
                });
#pragma warning restore 612, 618
        }
    }
}
