// <auto-generated />
using System;
using IrisManager.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IrisManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260805152909_SeedStylistsAndServiceRelations")]
    partial class SeedStylistsAndServiceRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IrisManager.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StylistId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("IrisManager.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "maria@correo.com",
                            IsActive = true,
                            Name = "María Pérez",
                            Phone = "809-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Email = "juan@correo.com",
                            IsActive = true,
                            Name = "Juan Rodríguez",
                            Phone = "809-555-0202"
                        });
                });

            modelBuilder.Entity("IrisManager.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 45,
                            Name = "Lavado y Secado",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 60,
                            Name = "Corte de Cabello (Dama)",
                            Price = 800m
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 30,
                            Name = "Corte de Cabello (Caballero)",
                            Price = 400m
                        },
                        new
                        {
                            Id = 4,
                            DurationMinutes = 30,
                            Name = "Corte de Puntas",
                            Price = 300m
                        },
                        new
                        {
                            Id = 5,
                            DurationMinutes = 90,
                            Name = "Peinado Elaborado / Eventos",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 6,
                            DurationMinutes = 120,
                            Name = "Tinte Completo",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 7,
                            DurationMinutes = 60,
                            Name = "Retoque de Raíces",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 8,
                            DurationMinutes = 180,
                            Name = "Highlights / Rayitos",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 9,
                            DurationMinutes = 240,
                            Name = "Balayage",
                            Price = 4500m
                        },
                        new
                        {
                            Id = 10,
                            DurationMinutes = 180,
                            Name = "Aplicación de Keratina",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 11,
                            DurationMinutes = 120,
                            Name = "Cirugía Capilar / Botox",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 12,
                            DurationMinutes = 45,
                            Name = "Tratamiento Profundo (Mascarilla)",
                            Price = 600m
                        },
                        new
                        {
                            Id = 13,
                            DurationMinutes = 45,
                            Name = "Manicura Regular",
                            Price = 400m
                        },
                        new
                        {
                            Id = 14,
                            DurationMinutes = 60,
                            Name = "Pedicura Regular",
                            Price = 600m
                        },
                        new
                        {
                            Id = 15,
                            DurationMinutes = 120,
                            Name = "Uñas Acrílicas",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 16,
                            DurationMinutes = 90,
                            Name = "Relleno de Acrílico",
                            Price = 900m
                        },
                        new
                        {
                            Id = 17,
                            DurationMinutes = 60,
                            Name = "Esmaltado en Gel",
                            Price = 700m
                        },
                        new
                        {
                            Id = 18,
                            DurationMinutes = 30,
                            Name = "Retiro de Acrílico / Gel",
                            Price = 300m
                        },
                        new
                        {
                            Id = 19,
                            DurationMinutes = 20,
                            Name = "Diseño y Depilación de Cejas",
                            Price = 300m
                        },
                        new
                        {
                            Id = 20,
                            DurationMinutes = 30,
                            Name = "Tintado de Cejas",
                            Price = 400m
                        },
                        new
                        {
                            Id = 21,
                            DurationMinutes = 30,
                            Name = "Depilación Facial (Cera)",
                            Price = 500m
                        },
                        new
                        {
                            Id = 22,
                            DurationMinutes = 120,
                            Name = "Postura de Pestañas (Pelo a Pelo)",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 23,
                            DurationMinutes = 90,
                            Name = "Maquillaje Profesional",
                            Price = 2500m
                        });
                });

            modelBuilder.Entity("IrisManager.Domain.Entities.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stylists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ana@correo.com",
                            IsActive = true,
                            Name = "Ana López",
                            Phone = "809-555-0101",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 2,
                            Email = "sofia@correo.com",
                            IsActive = true,
                            Name = "Sofía Martínez",
                            Phone = "809-555-0102",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 3,
                            Email = "lucia@correo.com",
                            IsActive = true,
                            Name = "Lucía Fernández",
                            Phone = "809-555-0103",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 4,
                            Email = "raquel@correo.com",
                            IsActive = true,
                            Name = "Raquel Vargas",
                            Phone = "809-555-0104",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 5,
                            Email = "marta@correo.com",
                            IsActive = true,
                            Name = "Marta Gómez",
                            Phone = "809-555-0201",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 6,
                            Email = "laura@correo.com",
                            IsActive = true,
                            Name = "Laura Díaz",
                            Phone = "809-555-0202",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 7,
                            Email = "elena@correo.com",
                            IsActive = true,
                            Name = "Elena Pérez",
                            Phone = "809-555-0203",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 8,
                            Email = "valeria@correo.com",
                            IsActive = true,
                            Name = "Valeria Castro",
                            Phone = "809-555-0204",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 9,
                            Email = "carmen@correo.com",
                            IsActive = true,
                            Name = "Carmen Ruiz",
                            Phone = "809-555-0301",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 10,
                            Email = "rosa@correo.com",
                            IsActive = true,
                            Name = "Rosa Sánchez",
                            Phone = "809-555-0302",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 11,
                            Email = "patricia@correo.com",
                            IsActive = true,
                            Name = "Patricia Ramírez",
                            Phone = "809-555-0303",
                            Specialty = ""
                        },
                        new
                        {
                            Id = 12,
                            Email = "daniela@correo.com",
                            IsActive = true,
                            Name = "Daniela Medina",
                            Phone = "809-555-0304",
                            Specialty = ""
                        });
                });

            modelBuilder.Entity("ServiceStylist", b =>
                {
                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.Property<int>("StylistsId")
                        .HasColumnType("int");

                    b.HasKey("ServicesId", "StylistsId");

                    b.ToTable("ServiceStylist");

                    b.HasData(
                        new
                        {
                            ServicesId = 1,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 1,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 1,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 1,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 2,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 2,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 2,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 2,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 3,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 3,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 3,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 3,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 4,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 4,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 4,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 4,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 5,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 5,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 5,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 5,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 6,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 6,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 6,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 6,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 7,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 7,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 7,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 7,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 8,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 8,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 8,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 8,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 9,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 9,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 9,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 9,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 10,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 10,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 10,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 10,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 11,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 11,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 11,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 11,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 12,
                            StylistsId = 1
                        },
                        new
                        {
                            ServicesId = 12,
                            StylistsId = 2
                        },
                        new
                        {
                            ServicesId = 12,
                            StylistsId = 3
                        },
                        new
                        {
                            ServicesId = 12,
                            StylistsId = 4
                        },
                        new
                        {
                            ServicesId = 13,
                            StylistsId = 5
                        },
                        new
                        {
                            ServicesId = 13,
                            StylistsId = 6
                        },
                        new
                        {
                            ServicesId = 13,
                            StylistsId = 7
                        },
                        new
                        {
                            ServicesId = 13,
                            StylistsId = 8
                        },
                        new
                        {
                            ServicesId = 14,
                            StylistsId = 5
                        },
                        new
                        {
                            ServicesId = 14,
                            StylistsId = 6
                        },
                        new
                        {
                            ServicesId = 14,
                            StylistsId = 7
                        },
                        new
                        {
                            ServicesId = 14,
                            StylistsId = 8
                        },
                        new
                        {
                            ServicesId = 15,
                            StylistsId = 5
                        },
                        new
                        {
                            ServicesId = 15,
                            StylistsId = 6
                        },
                        new
                        {
                            ServicesId = 15,
                            StylistsId = 7
                        },
                        new
                        {
                            ServicesId = 15,
                            StylistsId = 8
                        },
                        new
                        {
                            ServicesId = 16,
                            StylistsId = 5
                        },
                        new
                        {
                            ServicesId = 16,
                            StylistsId = 6
                        },
                        new
                        {
                            ServicesId = 16,
                            StylistsId = 7
                        },
                        new
                        {
                            ServicesId = 16,
                            StylistsId = 8
                        },
                        new
                        {
                            ServicesId = 17,
                            StylistsId = 5
                        },
                        new
                        {
                            ServicesId = 17,
                            StylistsId = 6
                        },
                        new
                        {
                            ServicesId = 17,
                            StylistsId = 7
                        },
                        new
                        {
                            ServicesId = 17,
                            StylistsId = 8
                        },
                        new
                        {
                            ServicesId = 18,
                            StylistsId = 5
                        },
                        new
                        {
                            ServicesId = 18,
                            StylistsId = 6
                        },
                        new
                        {
                            ServicesId = 18,
                            StylistsId = 7
                        },
                        new
                        {
                            ServicesId = 18,
                            StylistsId = 8
                        },
                        new
                        {
                            ServicesId = 19,
                            StylistsId = 9
                        },
                        new
                        {
                            ServicesId = 19,
                            StylistsId = 10
                        },
                        new
                        {
                            ServicesId = 19,
                            StylistsId = 11
                        },
                        new
                        {
                            ServicesId = 19,
                            StylistsId = 12
                        },
                        new
                        {
                            ServicesId = 20,
                            StylistsId = 9
                        },
                        new
                        {
                            ServicesId = 20,
                            StylistsId = 10
                        },
                        new
                        {
                            ServicesId = 20,
                            StylistsId = 11
                        },
                        new
                        {
                            ServicesId = 20,
                            StylistsId = 12
                        },
                        new
                        {
                            ServicesId = 21,
                            StylistsId = 9
                        },
                        new
                        {
                            ServicesId = 21,
                            StylistsId = 10
                        },
                        new
                        {
                            ServicesId = 21,
                            StylistsId = 11
                        },
                        new
                        {
                            ServicesId = 21,
                            StylistsId = 12
                        },
                        new
                        {
                            ServicesId = 22,
                            StylistsId = 9
                        },
                        new
                        {
                            ServicesId = 22,
                            StylistsId = 10
                        },
                        new
                        {
                            ServicesId = 22,
                            StylistsId = 11
                        },
                        new
                        {
                            ServicesId = 22,
                            StylistsId = 12
                        },
                        new
                        {
                            ServicesId = 23,
                            StylistsId = 9
                        },
                        new
                        {
                            ServicesId = 23,
                            StylistsId = 10
                        },
                        new
                        {
                            ServicesId = 23,
                            StylistsId = 11
                        },
                        new
                        {
                            ServicesId = 23,
                            StylistsId = 12
                        });
                });

            modelBuilder.Entity("IrisManager.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("IrisManager.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IrisManager.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IrisManager.Domain.Entities.Stylist", "Stylist")
                        .WithMany()
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("Stylist");
                });
#pragma warning restore 612, 618
        }
    }
}
