<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IrisManager.Domain\IrisManager.Domain.csproj" />
    <ProjectReference Include="..\IrisManager.Infrastructure\IrisManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
